"""add project table

Revision ID: 7cb6a4cde188
Revises: f06af3f36e45
Create Date: 2025-10-10 22:27:55.924139

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7cb6a4cde188'
down_revision: Union[str, Sequence[str], None] = 'f06af3f36e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'status',
            sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', name='project_status'),
            nullable=False,
        ),
        sa.Column(
            'create_time',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('complete_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('person_in_charge', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['person_in_charge'], ['users.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
